import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { API_BASE_URL, apiFetch } from "../lib/api";

type Photo={walkthrough_id:number;photo:string;photo_url:string|null;location:string;completed_at:string;item_count:number};
type Item={id:number;walkthrough_id:number;item_number:number;photo:string|null;location:string;vendor:string|null;manufacturer:string|null;manufacturer_part_number:string|null;vendor_part_number:string|null;part_number:string|null;description:string|null;size_specification:string|null;package_quantity:string|null;completed_at?:string;walkthrough_completed_at:string};
type Detail={location:string;photo_count:number;item_count:number;photos:Photo[];items:Item[]};
function date(v:string){const d=new Date(/(?:Z|[+-]\d{2}:?\d{2})$/i.test(v)?v:`${v}Z`);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
export default function LocationDetail(){
 const p=useLocalSearchParams<{customerId?:string;customerName?:string;location?:string}>(); const id=Number(p.customerId||0); const location=typeof p.location==="string"?p.location:"Unassigned"; const customer=typeof p.customerName==="string"?p.customerName:"Customer";
 const [detail,setDetail]=useState<Detail|null>(null); const [loading,setLoading]=useState(true); const [viewer,setViewer]=useState<Photo|null>(null);
 useEffect(()=>{(async()=>{try{const r=await apiFetch(`${API_BASE_URL}/api/customers/${id}/locations/detail?name=${encodeURIComponent(location)}`);const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Location unavailable");setDetail(d.detail)}catch(e){Alert.alert("Unable to load location",e instanceof Error?e.message:"Location unavailable")}finally{setLoading(false)}})()},[id,location]);
 return <SafeAreaView style={s.safe}><View style={s.container}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.title}>{location}</Text><Text numberOfLines={1} style={s.subtitle}>{customer}</Text></View></View>
 {loading?<View style={s.center}><ActivityIndicator size="large" color="#3B82F6"/></View>:detail?<ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
  <View style={s.summary}><Text style={s.summaryTitle}>Location Summary</Text><Text style={s.summaryText}>{detail.photo_count} photos • {detail.item_count} inventory items</Text></View>
  <Text style={s.section}>Photos</Text><View style={s.grid}>{detail.photos.map((photo,index)=><Pressable key={`${photo.walkthrough_id}-${photo.photo}`} onPress={()=>photo.photo_url&&setViewer(photo)} style={s.photoCard}>{photo.photo_url?<Image source={{uri:photo.photo_url}} style={s.image}/>:<View style={[s.image,s.missing]}><Text style={s.missingText}>Photo unavailable</Text></View>}<View style={s.overlay}><Text style={s.overlayText}>#{index+1} • {photo.item_count} items</Text></View></Pressable>)}</View>
  <Text style={s.section}>Inventory Items</Text>{detail.items.map((item,index)=><View key={item.id} style={s.item}><View style={s.itemHeader}><View style={s.num}><Text style={s.numText}>{index+1}</Text></View><View style={{flex:1}}><Text style={s.itemTitle}>{item.description||item.manufacturer_part_number||item.vendor_part_number||item.part_number||"Inventory Item"}</Text><Text style={s.itemDate}>Walkthrough #{item.walkthrough_id} • {date(item.walkthrough_completed_at)}</Text></View></View>{item.vendor?<Text style={s.line}><Text style={s.label}>Vendor: </Text>{item.vendor}</Text>:null}{item.manufacturer?<Text style={s.line}><Text style={s.label}>Manufacturer: </Text>{item.manufacturer}</Text>:null}{item.manufacturer_part_number?<Text style={s.line}><Text style={s.label}>Manufacturer Part #: </Text>{item.manufacturer_part_number}</Text>:null}{item.vendor_part_number?<Text style={s.line}><Text style={s.label}>Vendor Part #: </Text>{item.vendor_part_number}</Text>:null}{item.size_specification?<Text style={s.line}><Text style={s.label}>Size: </Text>{item.size_specification}</Text>:null}</View>)}
 </ScrollView>:<View style={s.center}><Text style={s.empty}>Location unavailable.</Text></View>}</View>
 <Modal visible={viewer!==null} animationType="fade" presentationStyle="pageSheet" onRequestClose={()=>setViewer(null)}><View style={s.viewer}><View style={s.viewerHeader}><Pressable onPress={()=>setViewer(null)} style={s.close}><Text style={s.closeText}>Close</Text></Pressable><Text style={s.viewerTitle}>{viewer?.photo}</Text><View style={{width:68}}/></View>{viewer?.photo_url?<Image source={{uri:viewer.photo_url}} resizeMode="contain" style={s.viewerImage}/>:null}</View></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0B1220"},container:{flex:1,paddingHorizontal:20,paddingTop:14},header:{flexDirection:"row",alignItems:"center",marginBottom:18},back:{width:46,height:46,borderRadius:14,backgroundColor:"#17243A",borderWidth:1,borderColor:"#31547D",alignItems:"center",justifyContent:"center",marginRight:13},backText:{color:"#FFF",fontSize:34,lineHeight:36,marginTop:-3},title:{color:"#FFF",fontSize:24,fontWeight:"800"},subtitle:{color:"#94A3B8",fontSize:14,marginTop:3},content:{paddingBottom:30},summary:{backgroundColor:"#14243A",borderRadius:18,borderWidth:1,borderColor:"#31547D",padding:16,marginBottom:18},summaryTitle:{color:"#FFF",fontSize:18,fontWeight:"800"},summaryText:{color:"#BFDBFE",marginTop:6},section:{color:"#FFF",fontSize:19,fontWeight:"800",marginBottom:11},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginBottom:22},photoCard:{width:"48%",aspectRatio:1,borderRadius:16,overflow:"hidden",borderWidth:1,borderColor:"#304B6A",backgroundColor:"#121C2D"},image:{width:"100%",height:"100%"},missing:{alignItems:"center",justifyContent:"center"},missingText:{color:"#718096"},overlay:{position:"absolute",left:7,right:7,bottom:7,borderRadius:10,backgroundColor:"rgba(6,18,31,.88)",padding:7},overlayText:{color:"#FFF",fontSize:11,fontWeight:"800"},item:{backgroundColor:"#121C2D",borderRadius:17,borderWidth:1,borderColor:"#26364F",padding:15,marginBottom:11},itemHeader:{flexDirection:"row",alignItems:"flex-start",marginBottom:12},num:{width:32,height:32,borderRadius:10,backgroundColor:"#1D4ED8",alignItems:"center",justifyContent:"center",marginRight:10},numText:{color:"#FFF",fontWeight:"800"},itemTitle:{color:"#FFF",fontSize:15,fontWeight:"800"},itemDate:{color:"#718096",fontSize:11,marginTop:4},line:{color:"#D8E2F0",fontSize:13,lineHeight:20,marginTop:3},label:{color:"#8FA1B9",fontWeight:"700"},center:{flex:1,alignItems:"center",justifyContent:"center"},empty:{color:"#94A3B8"},viewer:{flex:1,backgroundColor:"#02070D"},viewerHeader:{minHeight:68,flexDirection:"row",alignItems:"center",paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:"#1C2D43"},close:{width:68,minHeight:40,borderRadius:12,backgroundColor:"#17283C",alignItems:"center",justifyContent:"center"},closeText:{color:"#BFD5EA",fontWeight:"800"},viewerTitle:{flex:1,color:"#FFF",textAlign:"center",fontWeight:"800"},viewerImage:{flex:1,width:"100%"}});
